### ISSUE TITLE
As a user, I can save changes in the file in the same file or as other file.

### ISSUE THREAD

**Issue by ErykWalter** [lucapl/TextTransformer#60]
# Acceptance criterion:
- User can click Ctrl+S to save changes in a file
- User can select in a menu "Save" option
- User can select in a menu "Save as" option

# Tasks:
- [ ] Add a shortcut Ctrl+S for saving
- [ ] Add save option to menu
- [ ] Add "save as" option to menu
- [ ] Implement method to write a file
