### ISSUE TITLE
As a user, I can create empty text file and input text to it.

### ISSUE THREAD

**Issue by ErykWalter** [lucapl/TextTransformer#65]
# Acceptance criteria:
- There is option in menu "New file"
- User can create new file by clicking Ctrl+N
- There should be some indicator where user inputs the text
- User should be able to see inputted text

# Tasks:
- [ ] Add option to open new file in the menu
- [ ] Add a shortcut Ctrl+N to open new file 
- [ ] Add textbox for input
